#!/bin/bash

set -eu
set -o pipefail

if [ "$#" -eq 2 ]
then
    H="$1"
    E="$2"
    T=""
elif [ "$#" -eq 3 ]
then
    H="$1"
    T="$2"
    E="$3"
else
    echo "$0 <IP address> [token] <endpoint>" >&2
    echo
    exit 1
fi

if [[ ! -v XLED_DEBUG ]]
then
    if [ -t 1 ]
    then
        XLED_DEBUG_INTERNAL=1
    else
        XLED_DEBUG_INTERNAL=0
    fi
else
    XLED_DEBUG_INTERNAL="$XLED_DEBUG"
    unset XLED_DEBUG
fi

if [ -z "$T" ]
then
    T=$(./auth "$H")
fi


if [ "$XLED_DEBUG_INTERNAL" -ne 0 ]
then
    echo "GET $E" >&2
    curl --silent -H "Content-Type: application/json" -H "X-Auth-Token: $T" "http://$H/xled/v1/$E" | jq
else
    curl --silent -H "Content-Type: application/json" -H "X-Auth-Token: $T" "http://$H/xled/v1/$E"
fi
